version: "3.8"

services:
  backend:
    build:
      context: ./music_generation
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./music_generation:/app
    ports:
      - "8000:8000"
   
  frontend:
    build: 
      context: ./music_frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./music_frontend:/app
    ports:
      - "3000:3000"
